python main.py \
--dim 256 --dropout 0.3 --layers 2 \
--vision-backbone resnet34 \
--mode train \
--loss uncertainty_loss \
--epochs 50 --batch_size 16 \
--vision_num_classes 14 --num_classes 1 \
--data_pairs partial_ehr_cxr \
--data_ratio 1.0 \
--task in-hospital-mortality \
--labels_set mortality \
--fusion_type attention \
--save_dir checkpoints/mortality/attention_partial
